spring:
  datasource:
    url : jdbc:h2:mem:taskmandb
    driverClassName : org.h2.Driver
    username : user
    password : password
    database-platform : org.hibernate.dialect.H2Dialect

server:
  port : 8081

jwt : 
  header : Authorization
  secret : secret-key
    